#!/bin/bash

PATTERN=$1
DIR="${2:-.}"

if [ -t 1 ] ; then
    GREP_OPTS="--color=always $GREP_OPTS"
else
    GREP_OPTS="$GREP_OPTS"
fi

(zgrep $GREP_OPTS -hT "$PATTERN" "$DIR"/*.gz ; grep $GREP_OPTS -hT "$PATTERN" "$DIR"/* ) | sort -k1,2
